### ISSUE TITLE
Create eslint-plugin-hpe-design-system

### ISSUE THREAD

**Issue by taysea** [grommet/eslint-plugin-grommet#30]
Add config rules that are specific to HPE Design System. Starting an issue to create a running list of rules:
- [x] Suggestion for recommended icon usage, ex. "Prefer HomeRounded to Home", "Use Down instead of FormDown" (and any other form icons) https://github.com/grommet/eslint-plugin-hpe-design-system/issues/2, https://github.com/grommet/eslint-plugin-hpe-design-system/issues/3
- [x] Check for custom colors/HEX values -- non theme values: just warn or info in grommet but maybe use "error" in design system: https://github.com/grommet/eslint-plugin-grommet/issues/51
- [x] Check for `size` on Headings / other typography elements: https://github.com/grommet/eslint-plugin-hpe-design-system/issues/1
- [x] Avoid use of `style` prop: https://github.com/grommet/eslint-plugin-grommet/issues/35
- Is there a way to check if a prop someone has applied is already the default prop for that component? and if so, suggest they can remove it: TBD
- [x] Check for px values on size props like pad/margin/gap/width/height etc.: https://github.com/grommet/eslint-plugin-grommet/issues/52

**Comment by halocline** [comment]
Discussion points:
- [ ] Do HPE Design System rules belong on eslint-plugin-grommet? Or should eslint-plugin-grommet only contain rules related to general Grommet and accessibility best practices?
- [ ] When should a rule be a warning vs. error?
- [ ] @taysea any other discussion points?

**Comment by ericsoderberghp** [comment]
Good questions!
If we expect to have more than just a couple of rules, I'm wondering if we should have eslint-plugin-hpe-design-system?

**Comment by taysea** [comment]
Right now I'm leaning towards creating `eslint-plugin-hpe-design-system`. It should extend the "recommended" config from eslint-plugin-grommet but exist as its own repo since rules will be more specific to HPE, as opposed to open source community.

Aligns with mentality to keep Grommet "open-source" focused.

**Comment by taysea** [comment]
eslint-plugin-hpe-design-system has been created: https://github.com/grommet/eslint-plugin-hpe-design-system/tree/main

Before closing this, I want to discuss the remaining checkbox items and if they're relevant more to grommet or HPE Design System

**Comment by taysea** [comment]
Closing this, issues have been created.
